---
title: "About"
---

#### EMPLOYMENT:
Student Trainee (Health Insurance) / Pathways Internship Program, Centers for Medicare and Medicaid Services (CMS), Center for Medicaid and CHIP Services (CMCS), Data and Systems Group, Division of State Systems; Woodlawn, MD; May 2024 – Current: Provide analytic support to researchers and lead staff responsible for compiling program data for State Medicaid and CHIP Services programs; assist in production of technical briefings for senior officials; collaborate with staff analysts in data gathering, organizing, and interpreting results for outward facing tools for program implementation.   

Research Intern, Safe Kids Worldwide, Children’s National Medical Center; Silver Spring, MD; June 2023 – December 2023: Conducted data surveillance activities to include accessing and monitoring Centers for Disease Control (CDC) and National Highway Traffic Safety Administration (NHTSA) public databases; updated child injury statistics for 5+ Safe Kids’ priority injury risk area Fact Sheets; ascertained and verified 50+ legal outcomes relating to pediatric vehicular heatstroke deaths via court records and online searches; assisted planning committee for bi-annual child injury prevention Prev Con conference.

Assistant Teacher, Merritt Academy; Fairfax, VA; May 2021–Aug 2021; May 2022-Aug 2022: Provided classroom assistance to lead teacher; led activity set-up and clean-up; monitored playground activities; served as point-of-contact between teacher and parents; provided problem solving guidance to children.

#### SKILLS:
Ability to work as part of team; problem solving; empathetic attitude and ability to gain trust; communication between individuals and teams; time management; coalition building activities; nonprofit experience; group leadership and facilitation.

#### PROGRAMMING LANGUAGES/TECHNICAL SKILLS:
SAS; R; Python; Excel; SPSS; Data Visualization; Data Collection/Cleaning; Regression Analysis; Quantitative and Qualitative Analysis 

#### VOLUNTEER POSITIONS AND ACTIVITIES:
Family Advisory Board; A Foundation Building Strength for Nemaline Myopathy; March 2022 – Present: member of patient advocacy group to determine research funding priorities and policy agendas; provide feedback to research community and work with payer groups to establish positive relationships.

Group Facilitator, University of Virginia Hoos Connected Program; January 2023 – May 2024: completed 14-week leadership and training program in group leadership, management, and facilitation skill acquisition; lead groups of UVA underclassmen and transfer students each semester in weekly meetings to discuss campus acclimation and team building activities; participate in team meetings with other facilitators to discuss and problem-solve issues that arise and coordinate events for the larger community.

Language Consultant, University of Virginia Volunteers with International Students, Staff, and Scholars (UVA VISAS) Program; January 2023 – May 2024: provide 1:1 weekly meeting with international community to practice English language skills and provide a bridge within communities. 

#### EDUCATION:
Columbia University, Mailman School of Public Health, New York, NY (Incoming)
September 2024 – May 2026
Estimated Graduation Date: May 2026
Degree/Concentration: Master of Science / Biostatistics - Public Health Data Science

University of Virginia, Charlottesville, VA
August 2020 – May 2024
Degree, Major/Minor: Bachelor of Arts, Global Public Health/Statistics
GPA: 3.6

#### HONORS AND AWARDS:
Fall 2022, Spring 2023, Fall 2023:	University of Virginia, Dean’s List
Spring 2024:	University of Virginia, Graduate With Distinction
