---
title: "Is it a White Christmas?"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)

noaa_df = read_csv(file = "/Users/cameronchesbrough/camchesbro/nynoaadat.csv")


noaa_df = noaa_df %>%
  janitor::clean_names() %>%
  drop_na() %>%
  mutate(date = as.character(date)) %>%
  filter(date >= 2000) %>%
  filter(day(date)==25) %>%
  filter(month(date)==12)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot of Snowfall by Snowdepth:

```{r}
noaa_df %>%
  plot_ly(x = ~snwd, y = ~snow, type = "scatter", mode = "markers",
    text = ~date, alpha = 0.5) %>%
  layout(xaxis = list(title = "Snowdepth (mm)"),
         yaxis = list(title = "Snowfall (mm)"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Bargraph showing number of weather stations recording any amount of snowfall:

```{r}
noaa_df %>%
  filter(snow > 0) %>%
  count(date) %>%
  plot_ly(x = ~date, y = ~n, type = "bar", mode = "markers",
    alpha = 0.5) %>%
  layout(xaxis = list(title = "Christmas Year"),
         yaxis = list(title = "Number of Weather Stations"))
```

### Boxplot showing recorded snowfall in each weather station by each Christmas:

```{r}
noaa_df %>%
  plot_ly(x = ~date, y = ~snow, type = "box",
    alpha = 0.5) %>%
  layout(xaxis = list(title = "Christmas Year"),
         yaxis = list(title = "Snowfall (mm)"))
```

